name: branch-filter

on:
  push:
    branches:
      - dev-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a script
      run: echo "This runs only on commits to the dev branch."
