name: debug
on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: force fail
      run: |
        cat test.txt
    - name: Setup tmate session
      if: always()
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
      id: setup-tmate 
    - name: Wait for tmate actions
      if: always()
      timeout-minutes: 30
      run: |
        echo "SSH 접속 정보: ${{ steps.setup-tmate.outputs.ssh }}"
        echo "웹 접속 정보: ${{ steps.setup-tmate.outputs.web }}"