name: Example Workflow with Needs

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the project
        run: echo "Building the project..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the project
        run: echo "Testing the project..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the project
        run: echo "Deploying the project..."
