name: Example Workflow with Needs

on: push

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Test the project
        run: |
          echo "Test failed..."
          exit 1 

  deploy1:
    needs: test1
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the project
        run: echo "Deploying the project..."
 
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Test the project
        run: echo "Testing the project..."

  deploy2:
    needs: test2
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the project
        run: echo "Deploying the project..."
