name: string-function
on: push

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Check branch prefix
      if: endsWith(github.ref, '/prd')
      run: echo "Running on a dev branch"
