# workflow level
name: var-1
on: push

env:
  level: workflow

jobs:
  get-env-1:
    runs-on: ubuntu-latest
    steps:
    - name: check env
      run: echo "LEVEL ${{ env.level }}"
  
  get-env-2:
    runs-on: ubuntu-latest
    env:
      levle: job
    steps:
    - name: check env
      run: echo "LEVEL ${{ env.level }}"

  get-env-3:
    runs-on: ubuntu-latest
    env:
      levle: job
    steps:
    - name: check env
      run: echo "LEVEL ${{ env.level }}"
      env:
        level: step