# workflow level
name: var-2
on: push

env:
  level: workflow

jobs:
  get-var:
    runs-on: ubuntu-latest
    steps:
    - name: get var
      run: |
        echo "${{ var.level }}"
        echo ${{ var.level }}